"""
Upload the Zenodo deposit (3 ZIPs) for the dengue-climate-brazil-states repo.

Uses the Zenodo REST API:
  https://developers.zenodo.org/#rest-api

Authentication: personal access token with scope `deposit:write`.
The token is read from the environment variable ZENODO_TOKEN (loaded from .env
if python-dotenv is available). The .env file is gitignored; .env.example is
the template.

Usage (from repo root):
    python scripts/upload_zenodo.py            # create new deposit, upload, publish
    python scripts/upload_zenodo.py --dry-run  # validate inputs only, no API calls

After successful publish, the DOI and Record ID are printed. Update CITATION.cff,
README.md, and scripts/fetch_zenodo_data.py with those values.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

try:
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:
    pass

import requests

REPO_ROOT = Path(__file__).resolve().parents[1]
PACKAGES_DIR = Path(r"C:\Users\calebe\zenodo_packages")
MANIFEST_PATH = PACKAGES_DIR / "MANIFEST.json"

ZENODO_API = "https://zenodo.org/api"
REQUEST_TIMEOUT = 1800  # 30 min per file

METADATA = {
    "title": (
        "dengue-climate-brazil-states: large data files "
        "(climate CSVs and diagnostic figures)"
    ),
    "upload_type": "dataset",
    "publication_date": "2026-09-04",
    "description": (
        "Large data files referenced by the dengue-climate-brazil-states "
        "repository (Calebe Pereira Mendes et al., 2024-2026). "
        "This deposit contains: (1) a national-scale climate dataset "
        "(`inputs_climate_zenodo_todos_os_estados.csv`) used by the "
        "cross-state pipeline; (2) per-state diagnostic figures (37 SVG "
        "files) generated by the MVSE and DLNM pipelines for 6 Brazilian "
        "states. The associated GitHub repository at "
        "https://github.com/danielly-barbosa/dengue-climate-brazil-states "
        "provides the full reproducible code. SHA-256 checksums and file "
        "manifest are bundled in MANIFEST.json."
    ),
    "creators": [
        {
            "name": "Mendes, Calebe Pereira",
            "affiliation": "Doctoral program",
            "orcid": "",
        },
    ],
    "keywords": [
        "dengue",
        "climate",
        "Brazil",
        "InfoDengue",
        "MVSE",
        "DLNM",
        "epidemiology",
    ],
    "access_right": "open",
    "license": "cc-by-4.0",
    "version": "v1.0.0",
    "related_identifiers": [
        {
            "identifier": (
                "https://github.com/danielly-barbosa/dengue-climate-brazil-states"
            ),
            "relation": "isSupplementTo",
            "scheme": "url",
        },
    ],
}


def get_token() -> str:
    token = os.environ.get("ZENODO_TOKEN", "").strip()
    if not token:
        sys.stderr.write(
            "ERROR: ZENODO_TOKEN not set. Define it in .env (gitignored) or as "
            "an environment variable. See .env.example.\n"
        )
        sys.exit(2)
    return token


def load_manifest() -> dict:
    if not MANIFEST_PATH.exists():
        sys.stderr.write(f"ERROR: manifest not found at {MANIFEST_PATH}\n")
        sys.exit(1)
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def validate_packages(manifest: dict, dry_run: bool) -> None:
    print(f"[validate] manifest: {MANIFEST_PATH}")
    total_mb = 0.0
    for entry in manifest["files"]:
        path = PACKAGES_DIR / entry["name"]
        if not path.exists():
            sys.stderr.write(f"  MISSING: {path}\n")
            sys.exit(1)
        size_mb = path.stat().st_size / (1024 * 1024)
        total_mb += size_mb
        print(f"  OK {entry['name']}  {size_mb:8.2f} MB")
    print(f"[validate] total {total_mb:.2f} MB across {len(manifest['files'])} files")
    if dry_run:
        print("[dry-run] Skipping API calls.")
        sys.exit(0)


def create_deposit(token: str) -> dict:
    print("[create] new deposit")
    resp = requests.post(
        f"{ZENODO_API}/deposit/depositions",
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        json={},
        timeout=60,
    )
    if resp.status_code not in (200, 201):
        sys.stderr.write(f"ERROR creating deposit: HTTP {resp.status_code}\n{resp.text}\n")
        sys.exit(1)
    return resp.json()


def update_metadata(deposit_id: int, token: str) -> None:
    print("[metadata] update")
    resp = requests.put(
        f"{ZENODO_API}/deposit/depositions/{deposit_id}",
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        json={"metadata": METADATA},
        timeout=60,
    )
    if resp.status_code not in (200, 201):
        sys.stderr.write(f"ERROR updating metadata: HTTP {resp.status_code}\n{resp.text}\n")
        sys.exit(1)


def upload_file(bucket_url: str, token: str, file_path: Path) -> None:
    size_mb = file_path.stat().st_size / (1024 * 1024)
    print(f"[upload] {file_path.name}  ({size_mb:.2f} MB)")
    with open(file_path, "rb") as fh:
        resp = requests.put(
            f"{bucket_url}/{file_path.name}",
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/octet-stream",
            },
            data=fh,
            timeout=REQUEST_TIMEOUT,
        )
    if resp.status_code not in (200, 201):
        sys.stderr.write(
            f"ERROR uploading {file_path.name}: HTTP {resp.status_code}\n"
            f"{resp.text[:500]}\n"
        )
        sys.exit(1)
    print(f"  -> uploaded {file_path.name}")


def publish_deposit(deposit_id: int, token: str) -> dict:
    print("[publish]")
    resp = requests.post(
        f"{ZENODO_API}/deposit/depositions/{deposit_id}/actions/publish",
        headers={"Authorization": f"Bearer {token}"},
        timeout=60,
    )
    if resp.status_code not in (200, 202):
        sys.stderr.write(f"ERROR publishing: HTTP {resp.status_code}\n{resp.text}\n")
        sys.exit(1)
    return resp.json()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="validate inputs only; do not call the API",
    )
    args = parser.parse_args()

    manifest = load_manifest()
    validate_packages(manifest, dry_run=args.dry_run)
    if args.dry_run:
        return

    token = get_token()
    deposit = create_deposit(token)
    deposit_id = deposit["id"]
    bucket_url = deposit["links"]["bucket"]
    print(f"  -> deposit_id={deposit_id}")
    print(f"  -> bucket={bucket_url}")

    for entry in manifest["files"]:
        upload_file(bucket_url, token, PACKAGES_DIR / entry["name"])

    update_metadata(deposit_id, token)
    published = publish_deposit(deposit_id, token)

    doi = published.get("doi") or published.get("metadata", {}).get("doi")
    record_id = (
        published.get("record_id")
        or published.get("id")
        or deposit_id
    )
    record_url = (
        published.get("links", {}).get("record_html")
        or published.get("links", {}).get("self_html")
        or f"https://zenodo.org/record/{record_id}"
    )

    print()
    print("=" * 60)
    print(f"DOI       : {doi}")
    print(f"Record ID : {record_id}")
    print(f"URL       : {record_url}")
    print("=" * 60)
    print()
    print("Next steps:")
    print(f"  - Update CITATION.cff (identifiers[0].value) -> {doi}")
    print(f"  - Update README.md (Large files on Zenodo section) -> {doi}")
    print(f"  - Update scripts/fetch_zenodo_data.py ZENODO_RECORD_ID -> {record_id}")


if __name__ == "__main__":
    main()
